const mikuMotion = [
    "smile",
    "imagine_left",
    "imagine_right",
    "guide_normal",
    "guide_normal",
    "guide_normal",
    "guide_normal",
    "self_introduction",
    "idle_think",
    "point_left",
    "point_right",
];

const aiduchi = [
    "はい", "はい", "ええ", "えーえー", "まあ", "まあ", "そうですか",
    "そうですか", "そうなんですね", "そうなんですね", "そうでしたか",
    "そうでしたか", "なんでも話してください", "もっと教えてください",
    "もっと教えてください", "もっと教えてください", "そんなことがあったんですね",
    "そんなことがあったんですね", "そんなことがあったんですね",
    "それからどうなりましたか？", "それは大変でしたね",
    "ほかにどんなことがありましたか？", "ええ", "ええ", "うーん",
    "まあ！それはすごい", "あらあら", "そうだったんですね",
    "そうだったんですね", "そうだったんですね", "わかりました", "わかりました",
];

const allMikuMotion = [
    "ahaha",
    "ashiitai",
    "bikku",
    "bikkuri",
    "breath",
    "bye",
    "camera_pull",
    "camera_up",
    "ehehe",
    "fire",
    "greeting",
    "guide_happy",
    "guide_normal",
    "guide_sad",
    "idle_boredom",
    "idle_think",
    "idle_touch_clothes",
    "idle_yawn",
    "imagine_left",
    "imagine_right",
    "kissing",
    "laugh",
    "look_down",
    "menu_rotation",
    "miku_wait",
    "miku_wait2",
    "nandakana1",
    "nandakana2",
    "oko",
    "panel_off",
    "panel_on",
    "point_center_buttom",
    "point_center_center",
    "point_center_top",
    "point_left",
    "point_left_buttom",
    "point_left_center",
    "point_left_top",
    "point_right",
    "point_right_buttom",
    "point_right_center",
    "point_right_top",
    "pon",
    "rps_paper",
    "rps_rock",
    "rps_scissors",
    "sakeru",
    "self_introduction",
    "senobi",
    "smile",
    "snights",
    "surprise_normal",
    "surprise_small",
    "teleport1",
    "teleport2",
    "udegumi",
    "wait",
];


export { mikuMotion, aiduchi, allMikuMotion };